pipeline:

  publish-image:
    image: plugins/docker
    repo: sebastianhutter/haproxy
    dockerfile: Dockerfile
    tags:
      - "latest"
      - "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master]
      event: 
        exclude: [tag]

  publish-image-tag:
    image: plugins/docker
    repo: sebastianhutter/haproxy
    dockerfile: Dockerfile
    tags:
      - "${DRONE_TAG}"
      - "${DRONE_COMMIT_SHA:0:8}"
      - "latest"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
